service: geoterry-sls

custom:
  checkly_sls_config: ${file(./config/${self:provider.stage}.yml)}
  prune:
    automatic: true
    number: 3
  bundle:
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp && npm install --arch=x64 --platform=linux --target=10.15.0 sharp

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 20
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}

plugins:
  - serverless-bundle
  - serverless-prune-plugin

functions:
  otf-resize-image:
    handler: src/handler.triggerResizeImageToS3
    logRetentionInDays: 5
    timeout: 20
    events:
      - s3:
          bucket: ${self:custom.checkly_sls_config.aws.s3.staticBucket.name}
          event: s3:ObjectCreated:*
          rules:
            - prefix: geoterry/photo/original
          existing: true
    environment:
      ENVIRONMENT: ${self:provider.stage}
      CHECKLY_STORAGE_BUCKET: ${self:custom.checkly_sls_config.aws.s3.staticBucket.name}
