name: Serverless Deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.12.0
    - name: Install dependencies
      run: yarn install
    - name: Determine stage and deploy
      run: |
        if [[ "${{ github.ref }}" == 'refs/heads/master' ]]; then
          stage="production"
        elif [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
          stage="dev"
        else
          echo "Not deploying to any stage."
          exit 0
        fi
        echo "Deploying to stage: $stage"

        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

        if [[ "$stage" == "production" ]]; then
          yarn run deploy:prod
        else
          yarn run deploy:dev
        fi
